theme: jekyll-theme-cayman
title: PerSent
description: Personalized sentiment text classification
show_downloads: true

math_engine: mathjax
markdown: GFM
github:
  repository_url: https://github.com/pwr-personalization/nlp-sentify

article: docs/assets/PerSent_project_2022.pdf

plugins:
- jekyll-remote-theme