remote_theme: pages-themes/cayman@v0.2.0
title: PerSent
description: Personalized sentiment text classification
show_downloads: true

math_engine: mathjax
markdown: GFM
github:
  repository_url: https://github.com/pwr-personalization/retriever

article: docs/assets/PerSent_project_2022.pdf

plugins:
- jekyll-remote-theme